export type Project = {
  slug: string;
  title: string;
  status: "live" | "pre-launch" | "in-progress" | "open-source";
  role: string;
  timeline: string;
  summary: string;
  bullets: string[];
  stack: string[];
  image: string;
  imageAlt: string;
  links: Array<{ label: string; href: string }>;
  caseStudy: {
    tagline: string;
    problem: string;
    approach: string[];
    aiSplit: { claude: string[]; me: string[] };
    outcome: string;
    lessons: string[];
  };
};

export const projects: Project[] = [
  {
    slug: "medkompas",
    title: "MedKompas",
    status: "pre-launch",
    role: "Co-founder, full-stack",
    timeline: "5 months, part-time (Mar–Aug 2026)",
    summary:
      "Healthtech marketplace for medical tourism inside Russia. Map + filters + booking flow, connecting clinics with domestic and inbound patients. Deployed and taking patient enquiries, pre-launch on the clinic side.",
    bullets: [
      "Vite + React 19 + TypeScript on the client. One flow (map + booking), no SSR gymnastics over MapLibre.",
      "Express + Prisma + Postgres on the server. Wrote the JWT + bcrypt + rate-limit stack from scratch, no black-box RLS.",
      "MapLibre + OSM ingestion pipeline in Python (~800 LOC) instead of Google Maps. Free tiles, own styling, no vendor lock.",
      "i18next for RU/EN, CN/AR staged. Medical tourism is inbound too.",
      "Beget hosting, Apache + .htaccess. Clinics trust RU-hosted TLS.",
    ],
    stack: [
      "React 19",
      "TypeScript",
      "Vite",
      "Express",
      "Prisma",
      "PostgreSQL",
      "MapLibre",
      "i18next",
      "Python (ETL)",
    ],
    image: "/projects/medkompas.jpg",
    imageAlt: "MedKompas homepage — search bar, region stats, 17 doctors listed",
    links: [
      { label: "Read case study →", href: "/projects/medkompas" },
      { label: "medkompas13.ru →", href: "https://medkompas13.ru" },
    ],
    caseStudy: {
      tagline: "Healthtech marketplace shipped end-to-end in 4 months with a solo engineer + Claude Code.",
      problem: "My mother runs a medical clinic. Every year, thousands of Russians travel abroad for care they could get at home if only they knew where. Local marketplaces are broken — outdated maps, no filters, no real booking. I wanted to fix that specifically for Russia and to prove I could ship end-to-end.",
      approach: [
        "One flow, no distractions: map, filters, booking. No SEO gymnastics, so I picked Vite + React 19 instead of Next.js. Next would fight MapLibre's WebGL layer for nothing.",
        "Express + Prisma + Postgres on the server. Wrote the JWT + bcrypt + rate-limit stack from scratch — I do not trust generated auth code and RLS added complexity I did not need.",
        "MapLibre + OSM tiles instead of Google Maps. Free, self-hosted, own the styling. Wrote a ~800-line Python ETL to ingest OSM data + clinic overlays with Claude's help.",
        "i18next for RU/EN out of the gate. CN/AR staged for phase two — medical tourism goes both ways.",
        "Beget hosting with Apache + .htaccess. Boring, but clinics trust RU-hosted TLS more than anything shiny.",
      ],
      aiSplit: {
        claude: [
          "The full OSM ingestion pipeline in Python (~800 LOC) after I sketched the coordinate system.",
          "First drafts of React components and reducers.",
          "Migration scripts (which I then read line by line).",
          "The cron reminder job — caught a memory leak by tracing it to a stale Prisma connection.",
        ],
        me: [
          "Every schema decision. Claude tried to normalize the clinic table three times, I killed it every time.",
          "The whole auth flow. Password hashing, JWT expiry, token rotation, rate limits — no generated code touched prod.",
          "The 12-slide pastel sales deck for clinic meetings.",
          "Every merge review — I delete ~40% of Claude's first pass.",
        ],
      },
      outcome: "Pre-launch as of August 2026. Marketplace deployed to medkompas13.ru and taking patient enquiries; clinic onboarding is the next milestone, not a done deal. Total elapsed time from empty repo to a deployed product: ~4 months, part-time. Same scope in 2020 = one co-founder plus a year.",
      lessons: [
        "Tell Claude your stage in CLAUDE.md and it stops over-engineering. One paragraph killed 40% of the noise.",
        "Auth generated by AI is a landmine. Write it once by hand and never regret it.",
        "OSM tiles will save you hundreds of dollars a month vs Google. Worth the two-day setup.",
        "Clinic decision makers do not care about your stack. They care about RU-hosted TLS and one working booking flow.",
      ],
    },
  },
  {
    slug: "newforms",
    title: "newforms",
    status: "in-progress",
    role: "Solo dev · OVERKON side project",
    timeline: "In active development (Jul 2026)",
    summary:
      "Form-analytics SaaS for teams that outgrow Google Forms but do not want Typeform pricing. Built to keep my AI-assisted stack sharp between MedKompas releases.",
    bullets: [
      "Next.js 16 with App Router + Server Actions. Auth.js for magic-link + OAuth.",
      "Prisma with a single-migration philosophy. Every schema change is reviewed by hand before it hits prod.",
      "TanStack Table for the response viewer. Virtualized, keyboard-first, exportable.",
      "Owns its own CSV/JSON export path — no third-party analytics vendor.",
    ],
    stack: [
      "Next.js 16",
      "TypeScript",
      "Auth.js",
      "Prisma",
      "PostgreSQL",
      "TanStack Table",
      "Server Actions",
    ],
    image: "/projects/newforms.svg",
    imageAlt: "newforms dashboard mock — response stats, 14-day sparkline, response table",
    links: [{ label: "Read case study →", href: "/projects/newforms" }],
    caseStudy: {
      tagline: "Form-analytics SaaS for teams outgrowing Google Forms but not ready for Typeform pricing.",
      problem: "Every small team hits the same wall — Google Forms is free but the response viewer is a spreadsheet, and Typeform starts at $25/mo per seat before you get the analytics you actually want. There is a $10/mo sweet spot no one is serving cleanly for small ops teams.",
      approach: [
        "Next.js 16 with App Router + Server Actions. No REST layer, no tRPC — Server Actions are the mutation path.",
        "Auth.js for magic-link + Google OAuth. Prisma adapter, JWT session strategy, no custom cookie handling.",
        "Prisma with a single-migration philosophy — every schema change reviewed by hand before prod.",
        "TanStack Table for the response viewer. Virtualized past 200 rows, keyboard-first, exportable CSV/JSON.",
        "Own the CSV/JSON export path from day one. No third-party analytics vendor, no lock-in.",
      ],
      aiSplit: {
        claude: [
          "Server Actions boilerplate for CRUD (which I then compressed by ~30%).",
          "TanStack Table column defs and virtualization setup.",
          "Zod schemas for form-field validation.",
        ],
        me: [
          "Data model — Claude wanted five tables where three do the job.",
          "Auth.js configuration and session strategy pick.",
          "Rate limits on the submit endpoint. Real forms attract real spam.",
          "The pricing model and free-tier limits (not code, but the trade-offs).",
        ],
      },
      outcome: "In active development as of July 2026. v0.1 scope locked: 3 form types, response viewer, CSV/JSON export, magic-link auth. Beget VPS provisioning next.",
      lessons: [
        "Server Actions eliminate an entire folder of API routes. Do not add them back because a tutorial said so.",
        "Auth.js Prisma adapter beats writing your own session store when the app is not auth-first.",
        "TanStack Table is worth the learning curve for anything past 100 rows.",
      ],
    },
  },
  {
    slug: "claude-md-generator",
    title: "CLAUDE.md Generator",
    status: "open-source",
    role: "Author",
    timeline: "Built July 2026 · MIT",
    summary:
      "The single biggest lever on Claude Code output is a well-written CLAUDE.md. Most devs skip it or copy a stale template. This tool asks a few questions about your stack and stage, then generates an opinionated CLAUDE.md you can drop straight into a repo.",
    bullets: [
      "Modular by stack: Next.js, Prisma, Auth.js, MapLibre, Express, TanStack Table, Python ETL.",
      "Adjusts rules by project stage (pre-launch, growth, mature) — the same prompt should not apply to a 0-user prototype and a Series-B codebase.",
      "Adds explicit guardrails against Claude's known failure modes: over-normalization, retry storms, generated auth, docstring bloat.",
      "One-click copy or download. No sign-up, no tracking.",
    ],
    stack: ["Next.js 16", "React 19", "TypeScript", "Tailwind 4"],
    image: "/projects/claude-md-tool.jpg",
    imageAlt: "CLAUDE.md Generator UI — form + live markdown preview",
    links: [
      { label: "Open the tool →", href: "/tools/claude-md" },
      { label: "Read case study →", href: "/projects/claude-md-generator" },
      { label: "Playbook repo →", href: "https://github.com/Regat1ve/claude-code-playbook" },
    ],
    caseStudy: {
      tagline: "Free tool that generates an opinionated CLAUDE.md for your stack and stage. Runs in the browser, no signup.",
      problem: "Most repos I look at either skip CLAUDE.md entirely or paste a stale template from someone else's project. Both cases produce the same failure — Claude Code writes code that fights your stack, and you spend review time cutting it. The fix is a real CLAUDE.md written from experience, not generic best practices.",
      approach: [
        "One page, one form, one output. No sign-up, no server storage, no tracking beyond Vercel's built-in.",
        "Modular by stack: Next.js, React+Vite, Prisma, Auth.js, MapLibre, Express, TanStack Table, Python ETL, PostgreSQL, i18next.",
        "Rules parameterized by project stage — pre-launch bias toward simplicity, growth adds observability, mature adds zero-downtime migration rules.",
        "Each rule written from an actual Claude Code failure I lived through on MedKompas or newforms.",
        "Copy or download. Client-side generation, no round trip to a server.",
      ],
      aiSplit: {
        claude: [
          "The form scaffold (checkboxes, radios, layout).",
          "First draft of the copy/download logic.",
        ],
        me: [
          "Every single rule string. These have to come from real experience or the tool is worthless.",
          "The decision to keep it a static client component instead of a Next.js API route.",
          "The visual design — Claude wanted more color, I cut most of it.",
        ],
      },
      outcome: "Live at /tools/claude-md on this site. Open source under MIT. Rule set will grow as I ship more projects.",
      lessons: [
        "The best CLAUDE.md rule is one that names a specific past failure. Vague best-practice bullets do nothing.",
        "For a tool this focused, no backend beats a backend. Zero cost to run, zero privacy story to write.",
        "Ship the smallest thing that solves the problem for one person (me). If it survives that, expand.",
      ],
    },
  },
  {
    slug: "remote-work-radar",
    title: "remote-work-radar",
    status: "open-source",
    role: "Author",
    timeline: "Started July 2026 · MIT",
    summary:
      "OSS job board for developers locked out of Upwork, Mercor, Deel, and Contra. Aggregates remote-first feeds that do not gatekeep by country, filters US-only postings by default, flags scam patterns, and ships beginner-mode explanations for people writing their first cover letter.",
    bullets: [
      "Monorepo: Next.js 16 web app, Python 3.13 ETL, Prisma + Postgres schema package.",
      "Three live sources at ship: WeWorkRemotely RSS, RemoteOK JSON API, HN 'Who is hiring?' via Algolia search-by-date. 440 unique jobs on first pull.",
      "Deterministic dedup — hash(normalized title + normalized company). Same posting seen on two boards becomes one Job row with two source refs.",
      "Beginner mode is the default, not a feature flag. Glossary explains hourly vs retainer, 4 cover letter templates that do not fake seniority, scam detector flags 'training fee' asks.",
      "MCP server planned so Claude Code can search, score fit, and draft applications against the same DB.",
    ],
    stack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind",
      "Prisma",
      "PostgreSQL (Neon)",
      "Python 3.13",
      "psycopg 3",
      "BeautifulSoup",
      "feedparser",
      "httpx",
      "pytest",
    ],
    image: "/projects/remote-work-radar.jpg",
    imageAlt: "remote-work-radar /jobs page — filterable list of 540 remote postings with entry-level and scam badges",
    links: [
      { label: "Read case study →", href: "/projects/remote-work-radar" },
      { label: "Live site →", href: "https://remote-work-radar-web-g6sb.vercel.app" },
      { label: "Repo →", href: "https://github.com/Regat1ve/remote-work-radar" },
    ],
    caseStudy: {
      tagline: "Job aggregator I built because Upwork and Mercor stopped accepting Russian accounts. Also for anyone writing their first cover letter — beginner mode is the default.",
      problem: "In 2022 Upwork closed accounts across Russia, Belarus, and several other countries. Mercor, Deel, and Contra tightened their onboarding in 2025-2026. If you live in the wrong passport zone, the platforms that route freelance work at scale are simply not available. Meanwhile every remote job still exists — just not on those boards. There was no single place aggregating the feeds that do accept everyone.",
      approach: [
        "Monorepo from day one — apps/web (Next 16 + Tailwind), packages/db (Prisma + Postgres), services/etl (Python 3.13). One command runs everything.",
        "Three sources at ship (WeWorkRemotely RSS, RemoteOK JSON, HN 'Who is hiring?' via Algolia). Each writes a raw_snapshot JSONB so future parser fixes can replay against the original payload.",
        "Deterministic dedup: sha256(normalize(title) + normalize(company)). One Job row per real posting, N JobSourceRefs pointing at where it was seen. Cross-source duplicates fold naturally.",
        "Beginner mode is not a feature flag — it is the default UI. Glossary explains hourly, retainer, async, timezone overlap, USDC, Wise. Four cover letter templates, each honest about experience level. Scam detector flags upfront-fee asks, WhatsApp-only contacts, wire-transfer-before-contract patterns.",
        "Neon for Postgres — free tier auto-suspends after 5 minutes idle. ETL cold-starts it on the next fetch. Zero-cost hosting until real traffic.",
      ],
      aiSplit: {
        claude: [
          "Regex library for the parser (US-only patterns, hourly/salary ranges, skill keywords, scam flags) — I gave the patterns, Claude compiled them.",
          "Python source fetchers for WWR RSS and RemoteOK JSON. Simple shape, low ceiling for bugs.",
          "Prisma schema first draft. I then cut ~40% of it in a ponytail audit — seven speculative auth tables and six dead columns.",
          "Tailwind styling on the job cards and onboarding wizard.",
        ],
        me: [
          "Every dedup decision. Hash inputs, normalization rules, what counts as 'same job' vs 'same company different job'.",
          "The HN Algolia switch from /search (relevance) to /search_by_date, and the pipe-split parser that picks the token reading like a role instead of trusting position 1.",
          "The whole 'beginner mode is default' decision. Claude wanted a toggle, I killed it — the target user does not know to flip it.",
          "The cover letter templates. Each one comes from a real situation (first application, career switch, locked out, senior). Generic templates would have been worthless.",
        ],
      },
      outcome: "Live in the repo as of July 2026 — 440 unique jobs in the DB on first pull, dedup already catching cross-source matches. Deploy to Vercel and MCP server for Claude Code integration coming next.",
      lessons: [
        "Every source needs a raw_snapshot JSONB. Parsers get better; replay-friendly ingestion means you never have to re-fetch to re-parse.",
        "'Beginner mode' as an on/off toggle is a design smell. If the target user does not know to switch it on, it should be the default. Sophisticated users can hide the explanations later; strangers cannot make themselves knowledgeable.",
        "Dedup by hash(normalized fields) is worth ten minutes of design and saves a week of janky UPSERT logic downstream.",
      ],
    },
  },
  {
    slug: "timesheet-costs",
    title: "Timesheet & Costs",
    status: "open-source",
    role: "Solo — backend, frontend, code review",
    timeline: "Take-home brief, 4-day deadline, August 2026",
    summary:
      "Project time tracking where the money is always recomputed, never stored. Rates change retroactively by design, so a timesheet row keeps hours and a date — the cost is derived at read time from whichever rate was in force on that day. .NET 8 + MongoDB behind a React table, plus a written review of someone else's handler and page.",
    bullets: [
      "The rate is resolved inside the aggregation, not denormalised into the row. The brief allows backdated rate edits; a stored amount would go quietly stale and nobody would ever notice.",
      "Rows, totals and the row count come back in one $facet round trip. Sorting, skip and limit run before the $lookup, so the join only touches the page being shown.",
      "Money is Decimal128 in Mongo and decimal in C#, rounded half-to-even on both sides — because $round already rounds that way, and a report that disagrees with the row it sums is worse than one that is off by a kopeck.",
      "Business rules live in one pure class: the half-hour step, the 24-hour ceiling, the daily limit, the overtime flag past 12 hours, the closed-period lock. 34 unit tests hit it without a database in sight.",
      "Editing checks a version predicate inside the update filter. Two people on the same row means the second one is told, not silently overwritten.",
      "16 acceptance tests run against a real mongod via EphemeralMongo — the aggregation is the product here, and mocking it would have tested nothing.",
      "The second half of the brief was a review of existing code: 12 problems in the C# handler, 16 in the React page, each with the fixed version next to it.",
    ],
    stack: [".NET 8", "C#", "MongoDB", "React", "TypeScript", "Vite", "xUnit"],
    image: "/projects/timesheet-costs.jpg",
    imageAlt: "Timesheet table — date, employee, project, hours, rate and cost columns with a filtered total row",
    links: [
      { label: "Read case study →", href: "/projects/timesheet-costs" },
      { label: "Repo →", href: "https://github.com/Regat1ve/timesheet-costs" },
    ],
    caseStudy: {
      tagline: "A costing service where the number is derived, not remembered — and a code review that came with the fixes attached.",
      problem:
        "Track hours per employee per project, price them, report on them. The trap is one line in the brief: an hourly rate has a start date and can be changed after the fact. That single sentence rules out the obvious design, where the row stores the money it cost. There is no rate-change endpoint to hang a recalculation off, so a stored amount would drift away from the truth with nothing to catch it.",
      approach: [
        "Kept the row honest: hours, a date, who and which project. The rate that applied on that day is picked inside the pipeline with $sortArray plus $first, and the cost is computed from it on every read.",
        "Paid the read cost knowingly. Recomputing is more work per query than reading a stored field — but with the aggregation indexed and the join deferred until after paging, that work is bounded, and correctness is not.",
        "Matched the rounding on both sides of the wire. Mongo's $round is half-to-even, so the C# side uses MidpointRounding.ToEven rather than the default. Two rounding modes in one system is a bug that surfaces months later in a total nobody can explain.",
        "Pulled every rule out of the service into a class with no dependencies, so the interesting logic is testable without spinning anything up.",
        "Ran the acceptance tests against a real mongod instead of a mock. Everything worth getting wrong here lives inside the aggregation, and a mocked driver would have agreed with whatever I wrote.",
      ],
      aiSplit: {
        claude: [
          "First pass of the aggregation stages and the BsonDocument scaffolding, which is tedious to type and easy to typo.",
          "The React table, filters and dialogs.",
          "Boilerplate for the test fixtures and the seed data.",
        ],
        me: [
          "The decision to compute the cost at read time. The first draft stored it on the row, which is faster and wrong.",
          "Catching the rounding mismatch. Half-to-even on one side and half-away-from-zero on the other is invisible in tests with round numbers and obvious in production.",
          "Insisting on real integration tests. Mocking the driver would have made the suite green and meaningless.",
          "The review half: reading someone else's handler line by line and writing why each fix matters, not just what it changes.",
        ],
      },
      outcome:
        "Delivered inside the four-day window with 50 tests passing from a clean clone. Backdating a rate change moves every affected report immediately, which is the behaviour the brief asked for and the one a stored amount cannot give you.",
      lessons: [
        "If a value can be edited behind your back, storing its consequences is a bug on a delay. Derive it while you can still afford to.",
        "Rounding is part of the contract between the database and the application. Pick one mode and write down why.",
        "Page before you join. Sorting and limiting ahead of the $lookup is the difference between joining a page and joining a table.",
        "A code review is worth more with the corrected file attached. 'This is racy' starts an argument; a diff ends it.",
      ],
    },
  },
  {
    slug: "vitaly-card",
    title: "Card as a Service",
    status: "live",
    role: "Solo — schema, API, page, delivery",
    timeline: "Take-home brief, one day, August 2026",
    summary:
      "A business card that is a service, not a page. The content lives in PostgreSQL, GraphQL is the only way in, and the page a human sees is an ordinary client of that same API. One source of truth, no copy of the content sitting in the markup.",
    bullets: [
      "Code-first GraphQL: the schema is generated from TypeScript types, so the SDL cannot drift from the code. schema.gql is not committed — a generated file in git is a stale file waiting to happen.",
      "Relations resolve on demand. Asking for a name does not touch the links, skills or projects tables.",
      "The stack filter runs in PostgreSQL as an array operation. Fetching everything and filtering in Node is invisible at five rows and painful at five thousand.",
      "CI does not just run tests: it builds the image, starts it next to PostgreSQL, waits for /health to report the database up, then fires a real query and a deliberately broken mutation at it.",
      "That paid for itself three times over. Prisma would not boot on Alpine for want of OpenSSL, writing the schema file crashed the serverless build on a read-only filesystem, and the static page 404'd from a path that does not exist in the bundle. All three were green on my machine.",
      "The single HTML page is compiled into the build at prebuild instead of being served off disk, so nothing in production has to guess where a file landed.",
      "Skill levels are three honest steps — write it daily, shipped it once, tried it — rather than a percentage. NestJS and GraphQL sit on the bottom step, because this project is where I met them.",
    ],
    stack: ["NestJS", "GraphQL", "Prisma", "PostgreSQL", "TypeScript", "Docker", "GitHub Actions"],
    image: "/projects/vitaly-card.jpg",
    imageAlt: "Dark business card page — name, skill grid by category, project list, rendered from the GraphQL API",
    links: [
      { label: "Read case study →", href: "/projects/vitaly-card" },
      { label: "Open the card →", href: "https://vitaly-card.vercel.app" },
      { label: "Repo →", href: "https://github.com/Regat1ve/vitaly-card" },
    ],
    caseStudy: {
      tagline: "Build a business card with Git, TypeScript, NestJS, Prisma, GraphQL and Docker — so I built the card as a service and let the page be a client.",
      problem:
        "The brief listed a stack and asked for a card. The lazy reading is a static page with the stack listed in a footer. The useful reading is: the content is data, so put it in a database, expose it properly, and let the page render from the same API anyone else would call. That way the technologies are doing work instead of appearing in a list.",
      approach: [
        "Modelled the card first — profile, links, skills, projects, contact requests — then let the GraphQL schema fall out of those types. Code-first means one source, so the SDL and the code cannot disagree.",
        "Made the contact mutation actually write to the database, with validation that names the offending fields. A mutation that returns a stub proves nothing.",
        "Rate-limited it, because the card is public and the mutation writes. The stock throttler guard does not understand GraphQL context, so the request lookup is overridden.",
        "Pointed the health check at the database. 'ok' from a process that cannot see PostgreSQL is a green light that means nothing — the Docker HEALTHCHECK uses the same endpoint.",
        "Made CI start the container next to a real database and interrogate it. That is the only reason the three delivery bugs were found before a reviewer found them.",
      ],
      aiSplit: {
        claude: [
          "First pass of the resolvers, DTOs and the Prisma schema.",
          "The Dockerfile and compose skeleton.",
          "The static page markup before I rewrote the copy.",
        ],
        me: [
          "The decision to make the page a client of the API rather than a second copy of the content.",
          "Reading every CI failure as a real defect instead of a CI quirk — Alpine and OpenSSL, the read-only filesystem, the missing path. Each one would have broken for the reviewer too.",
          "Refusing to ship a percentage next to a skill. Three steps that mean something beat a number that means nothing.",
          "Leaving contactRequests out of the schema on purpose, so form submissions cannot be read back by strangers.",
        ],
      },
      outcome:
        "Live at vitaly-card.vercel.app with the sandbox open at /graphql and the service state at /health. Green CI here means the image builds, the container starts, and the API answers a real query — not that the files compiled.",
      lessons: [
        "Content in a database and a page that queries it is less work than content pasted into markup twice.",
        "A build that is only ever run on your own machine is not tested. A clean machine has no OpenSSL, no writable disk and none of your folders.",
        "Serverless is not a container. Anything that writes to the filesystem at boot will find that out for you.",
        "Say which skills are new. Putting GraphQL on the bottom step cost nothing and made the rest of the list believable.",
      ],
    },
  },
  {
    slug: "demo-lab",
    title: "Demo Lab",
    status: "live",
    role: "Author",
    timeline: "Built in one day, August 2026",
    summary:
      "Four working interfaces built to be clicked, not looked at: a scroll-driven 3D product page, an analytics dashboard, a store with a persistent cart, and a four-step booking flow.",
    bullets: [
      "AURORA — React Three Fiber scene: shader-displaced geometry, particle shell, procedural environment from lightformers. No external models, no HDR files. Scroll drives camera, distortion and palette.",
      "PULSE — analytics dashboard. Charts hand-written in SVG, no charting library. Crosshair tooltip, sortable table, filters. Palette validated for colour-vision deficiency before shipping.",
      "KŌRI — storefront. Category, price and stock filters, three sort modes, cart that survives a reload, promo codes and a free-shipping threshold.",
      "ATELIER — booking in four steps. Calendar with busy slots blocked, phone mask and validation, confirmation screen with the order summary.",
      "All four are statically prerendered. The 3D bundle is a dynamic import, so it never touches the first load of the other pages.",
    ],
    stack: ["Next.js 16", "React 19", "TypeScript", "React Three Fiber", "Three.js", "Tailwind 4", "SVG"],
    image: "/shots/demo-aurora.jpg",
    imageAlt: "AURORA demo — a reflective distorted sphere inside a wireframe cage on a dark field",
    links: [
      { label: "Open the demos →", href: "/demos" },
      { label: "Read case study →", href: "/projects/demo-lab" },
    ],
    caseStudy: {
      tagline: "Four clickable interfaces, built in a day, to replace “here are my screenshots” with “here, try it”.",
      problem:
        "A portfolio of finished products has a gap: a stranger cannot poke at them. MedKompas needs a clinic account, newforms is mid-build. I wanted four things a client could open in one click and immediately understand what I can do — across four different kinds of work, not four variations of a landing page.",
      approach: [
        "Picked four jobs that cover the real spread of client requests: a wow-factor product page, a B2B data screen, an e-commerce flow, and lead capture.",
        "3D scene built entirely from procedural geometry. drei's Environment fed by Lightformers gives real reflections with zero asset downloads — the page never waits on an HDR file.",
        "Dashboard charts written by hand in SVG. Two series, one axis, a legend, direct end labels, and a crosshair. The palette was run through a CVD validator before a single line was drawn.",
        "Store cart lives in localStorage behind try/catch, so a private window degrades to an in-memory cart instead of a blank screen.",
        "Booking data is generated from a seeded PRNG, so the server and the browser render the same thing and there is no hydration mismatch.",
      ],
      aiSplit: {
        claude: [
          "First pass of the Tailwind layouts for all four screens.",
          "Boilerplate for the sortable table and the filter reducers.",
          "The scaffold of the R3F scene, before I rebalanced the composition.",
        ],
        me: [
          "Every colour decision in the dashboard, and the choice to validate them instead of eyeballing.",
          "The call to kill the emissive on the 3D material — it was washing out every reflection and making the object read flat.",
          "Seeded randomness everywhere instead of Math.random, so renders stay pure and reproducible.",
          "Cutting the scope to four demos when the first plan had six.",
        ],
      },
      outcome:
        "Live at /demos since August 2026. Now the first link in every cold message: a client clicks, filters something, adds to a cart, and the conversation starts from what the code does rather than from my CV.",
      lessons: [
        "A metal material with no environment map looks dead. Lightformers cost nothing and fix it — an HDR file is not the only way to get reflections.",
        "Emissive fights reflection. If a surface looks flat, the self-illumination is usually the culprit, not the lighting.",
        "Seed your randomness in anything server-rendered. Math.random in a component is both a hydration bug and a lint error waiting to happen.",
        "Demos beat screenshots. A person who has clicked your filter already believes you can build filters.",
      ],
    },
  },
  {
    slug: "kuznets",
    title: "КУЗНЕЦ",
    status: "live",
    role: "Solo — design, code, art",
    timeline: "Built in one day, August 2026",
    summary:
      "A physics merge game set in a forge. Drop billets, fuse matching ones up an eight-step ladder from copper to mithril. The genre twist is Reforge: a heat meter that buys one hammer strike, welding any ingot to its nearest twin anywhere on the field.",
    bullets: [
      "Vanilla JS + matter.js, no build step. The same folder runs on Vercel and inside a Yandex.Games archive — nothing to compile, nothing to configure per host.",
      "Reforge fixes the genre's worst moment: a lone ingot buried under the pile with its pair unreachable. Heat builds from every fusion; a full meter spends on one targeted weld.",
      "Fixed 60 Hz timestep with a substep accumulator, so a 144 Hz laptop and a throttled phone run identical physics instead of drifting apart.",
      "The basin height adapts to the viewport shape — a tall phone gets a deeper forge — and the floor body moves with it rather than the field being letterboxed.",
      "Bodies are the ingots themselves, not circles wearing an ingot picture. Round bodies forced a disc backing under every sprite to hide the gaps between them; making the collision shape the trapezoid deleted the backing and the gaps in one move.",
      "Tier palette run through a colour-vision-deficiency validator before anything was rendered: worst adjacent pair ΔE 17.4 under deuteranopia. Warm and cool alternate up the ladder so neighbours never blur together.",
      "Sound is synthesised in WebAudio — a noise transient through a bandpass plus two detuned triangles, pitched by tier. No audio files ship at all, and it mutes on tab blur and during ads, as the platform requires.",
      "Yandex Games SDK is optional at runtime: leaderboard, interstitials and language detection when the platform is there, a plain game when it is not.",
    ],
    stack: ["Vanilla JS", "matter.js", "Canvas 2D", "WebAudio", "Python (Pillow)", "Yandex Games SDK"],
    image: "/shots/kuznets.jpg",
    imageAlt: "KUZNETS — coloured metal ingots piled at the bottom of a dark forge, score and heat meter above",
    links: [
      { label: "Play it →", href: "/games/kuznets" },
      { label: "Read case study →", href: "/projects/kuznets" },
    ],
    caseStudy: {
      tagline: "A merge game built in a day, from Blender render to a deployed URL, with one mechanic the genre does not have.",
      problem:
        "Merge games are the busiest shelf on Yandex.Games — Дино Дроп, Зомби: Слияние Оружия, Merge Mercs all sit in the top rows. That makes the format a good test: the rules are known, so the only thing left to judge is execution. It also has a well-known flaw. Sooner or later one ingot ends up buried with its only twin on the far side of the pile, and there is nothing you can do but wait to lose. I wanted to ship the genre properly and fix that specific moment.",
      approach: [
        "Checked the catalogue first instead of guessing. Merge titles were all over the front page, which settled the format before a line was written.",
        "Chose vanilla JS over a framework on purpose. The deliverable had to be a folder that a static host and a platform ZIP both accept, so a build step would have been pure cost.",
        "Designed Reforge as the answer to the buried-ingot problem: heat accrues from fusions, a full meter arms the hammer, and one click welds the chosen ingot to its nearest twin. A miss costs nothing — the hammer stays raised — because spending a full meter on a mis-tap would be worse than the problem it solves.",
        "Tuned the field by playing it, not by reasoning about it. The first basin held roughly ninety of the smallest ingots and the top half never filled, so the ladder was rescaled and the depth capped.",
        "Ran the physics loop on a fixed timestep after matter.js warned about variable deltas. Frame-rate-dependent physics is the kind of bug that only shows up on someone else's phone.",
      ],
      aiSplit: {
        claude: [
          "First pass of the matter.js wiring — bodies, walls, collision events.",
          "The WebAudio synth voices for the metal clang.",
          "Boilerplate for the Yandex SDK wrapper and the RU/EN string tables.",
        ],
        me: [
          "The Reforge mechanic — what it costs, what happens on a miss, and why a failed strike must not spend the meter.",
          "Killing eight separate Blender renders. Mirror-finish metal reflects an almost-black world, so silver and platinum came out black; one neutral render tinted per tier was both better looking and controllable.",
          "Refusing to keep patching the art around a round collision shape, and changing the shape instead. Every earlier fix — a disc backing, a zero-margin assert — was paying rent on the wrong decision.",
          "Deciding the chain multiplier was worth the volatility. A seven-link cascade paying +168 is the moment people replay for.",
        ],
      },
      outcome:
        "Live and playable in the browser and on a phone. A full run lands around three to four minutes, all eight tiers are reachable, and the whole thing weighs under half a megabyte including the physics engine.",
      lessons: [
        "Check the shop before designing. Ten minutes in the catalogue replaced a whole argument about what format to build.",
        "When the art keeps needing workarounds, the collision shape is usually the thing that is wrong. A disc painted under every ingot hid the gaps; making the body the ingot removed the reason for both.",
        "Never render a mirror metal against a dark world. Metallic 1.0 has no diffuse component, so the object shows you the room, and the room was black.",
        "Fixed timestep is not premature. Variable delta physics works perfectly on the machine you wrote it on and nowhere else.",
        "Give a spent resource a refund path. The hammer staying raised after a miss is three lines of code and it is the difference between a mechanic people use and one they are afraid of.",
      ],
    },
  },
];
