export type Project = {
  slug: string;
  title: string;
  status: "live" | "pre-launch" | "in-progress" | "open-source";
  role: string;
  timeline: string;
  summary: string;
  bullets: string[];
  stack: string[];
  image: string;
  imageAlt: string;
  links: Array<{ label: string; href: string }>;
  caseStudy: {
    tagline: string;
    problem: string;
    approach: string[];
    aiSplit: { claude: string[]; me: string[] };
    outcome: string;
    lessons: string[];
  };
};

export const projects: Project[] = [
  {
    slug: "medkompas",
    title: "MedKompas",
    status: "pre-launch",
    role: "Co-founder, full-stack",
    timeline: "4 months, part-time (Mar–Jul 2026)",
    summary:
      "Healthtech marketplace for medical tourism inside Russia. Map + filters + booking flow, connecting clinics with domestic and inbound patients. Onboarding first partner clinics right now.",
    bullets: [
      "Vite + React 19 + TypeScript on the client. One flow (map + booking), no SSR gymnastics over MapLibre.",
      "Express + Prisma + Postgres on the server. Wrote the JWT + bcrypt + rate-limit stack from scratch, no black-box RLS.",
      "MapLibre + OSM ingestion pipeline in Python (~800 LOC) instead of Google Maps. Free tiles, own styling, no vendor lock.",
      "i18next for RU/EN, CN/AR staged. Medical tourism is inbound too.",
      "Beget hosting, Apache + .htaccess. Clinics trust RU-hosted TLS.",
    ],
    stack: [
      "React 19",
      "TypeScript",
      "Vite",
      "Express",
      "Prisma",
      "PostgreSQL",
      "MapLibre",
      "i18next",
      "Python (ETL)",
    ],
    image: "/projects/medkompas.jpg",
    imageAlt: "MedKompas homepage — search bar, region stats, 17 doctors listed",
    links: [
      { label: "Read case study →", href: "/projects/medkompas" },
      { label: "medkompas13.ru →", href: "https://medkompas13.ru" },
    ],
    caseStudy: {
      tagline: "Healthtech marketplace shipped end-to-end in 4 months with a solo engineer + Claude Code.",
      problem: "My mother runs a medical clinic. Every year, thousands of Russians travel abroad for care they could get at home if only they knew where. Local marketplaces are broken — outdated maps, no filters, no real booking. I wanted to fix that specifically for Russia and to prove I could ship end-to-end.",
      approach: [
        "One flow, no distractions: map, filters, booking. No SEO gymnastics, so I picked Vite + React 19 instead of Next.js. Next would fight MapLibre's WebGL layer for nothing.",
        "Express + Prisma + Postgres on the server. Wrote the JWT + bcrypt + rate-limit stack from scratch — I do not trust generated auth code and RLS added complexity I did not need.",
        "MapLibre + OSM tiles instead of Google Maps. Free, self-hosted, own the styling. Wrote a ~800-line Python ETL to ingest OSM data + clinic overlays with Claude's help.",
        "i18next for RU/EN out of the gate. CN/AR staged for phase two — medical tourism goes both ways.",
        "Beget hosting with Apache + .htaccess. Boring, but clinics trust RU-hosted TLS more than anything shiny.",
      ],
      aiSplit: {
        claude: [
          "The full OSM ingestion pipeline in Python (~800 LOC) after I sketched the coordinate system.",
          "First drafts of React components and reducers.",
          "Migration scripts (which I then read line by line).",
          "The cron reminder job — caught a memory leak by tracing it to a stale Prisma connection.",
        ],
        me: [
          "Every schema decision. Claude tried to normalize the clinic table three times, I killed it every time.",
          "The whole auth flow. Password hashing, JWT expiry, token rotation, rate limits — no generated code touched prod.",
          "The 12-slide pastel sales deck for clinic meetings.",
          "Every merge review — I delete ~40% of Claude's first pass.",
        ],
      },
      outcome: "Pre-launch as of July 2026. Marketplace deployed to medkompas13.ru, partner-clinic contracts being finalized. Total elapsed time from empty repo to pre-launch: ~4 months, part-time. Same scope in 2020 = one co-founder plus a year.",
      lessons: [
        "Tell Claude your stage in CLAUDE.md and it stops over-engineering. One paragraph killed 40% of the noise.",
        "Auth generated by AI is a landmine. Write it once by hand and never regret it.",
        "OSM tiles will save you hundreds of dollars a month vs Google. Worth the two-day setup.",
        "Clinic decision makers do not care about your stack. They care about RU-hosted TLS and one working booking flow.",
      ],
    },
  },
  {
    slug: "newforms",
    title: "newforms",
    status: "in-progress",
    role: "Solo dev · OVERKON side project",
    timeline: "In active development (Jul 2026)",
    summary:
      "Form-analytics SaaS for teams that outgrow Google Forms but do not want Typeform pricing. Built to keep my AI-assisted stack sharp between MedKompas releases.",
    bullets: [
      "Next.js 16 with App Router + Server Actions. Auth.js for magic-link + OAuth.",
      "Prisma with a single-migration philosophy. Every schema change is reviewed by hand before it hits prod.",
      "TanStack Table for the response viewer. Virtualized, keyboard-first, exportable.",
      "Owns its own CSV/JSON export path — no third-party analytics vendor.",
    ],
    stack: [
      "Next.js 16",
      "TypeScript",
      "Auth.js",
      "Prisma",
      "PostgreSQL",
      "TanStack Table",
      "Server Actions",
    ],
    image: "/projects/newforms.svg",
    imageAlt: "newforms dashboard mock — response stats, 14-day sparkline, response table",
    links: [{ label: "Read case study →", href: "/projects/newforms" }],
    caseStudy: {
      tagline: "Form-analytics SaaS for teams outgrowing Google Forms but not ready for Typeform pricing.",
      problem: "Every small team hits the same wall — Google Forms is free but the response viewer is a spreadsheet, and Typeform starts at $25/mo per seat before you get the analytics you actually want. There is a $10/mo sweet spot no one is serving cleanly for small ops teams.",
      approach: [
        "Next.js 16 with App Router + Server Actions. No REST layer, no tRPC — Server Actions are the mutation path.",
        "Auth.js for magic-link + Google OAuth. Prisma adapter, JWT session strategy, no custom cookie handling.",
        "Prisma with a single-migration philosophy — every schema change reviewed by hand before prod.",
        "TanStack Table for the response viewer. Virtualized past 200 rows, keyboard-first, exportable CSV/JSON.",
        "Own the CSV/JSON export path from day one. No third-party analytics vendor, no lock-in.",
      ],
      aiSplit: {
        claude: [
          "Server Actions boilerplate for CRUD (which I then compressed by ~30%).",
          "TanStack Table column defs and virtualization setup.",
          "Zod schemas for form-field validation.",
        ],
        me: [
          "Data model — Claude wanted five tables where three do the job.",
          "Auth.js configuration and session strategy pick.",
          "Rate limits on the submit endpoint. Real forms attract real spam.",
          "The pricing model and free-tier limits (not code, but the trade-offs).",
        ],
      },
      outcome: "In active development as of July 2026. v0.1 scope locked: 3 form types, response viewer, CSV/JSON export, magic-link auth. Beget VPS provisioning next.",
      lessons: [
        "Server Actions eliminate an entire folder of API routes. Do not add them back because a tutorial said so.",
        "Auth.js Prisma adapter beats writing your own session store when the app is not auth-first.",
        "TanStack Table is worth the learning curve for anything past 100 rows.",
      ],
    },
  },
  {
    slug: "claude-md-generator",
    title: "CLAUDE.md Generator",
    status: "open-source",
    role: "Author",
    timeline: "Built July 2026 · MIT",
    summary:
      "The single biggest lever on Claude Code output is a well-written CLAUDE.md. Most devs skip it or copy a stale template. This tool asks a few questions about your stack and stage, then generates an opinionated CLAUDE.md you can drop straight into a repo.",
    bullets: [
      "Modular by stack: Next.js, Prisma, Auth.js, MapLibre, Express, TanStack Table, Python ETL.",
      "Adjusts rules by project stage (pre-launch, growth, mature) — the same prompt should not apply to a 0-user prototype and a Series-B codebase.",
      "Adds explicit guardrails against Claude's known failure modes: over-normalization, retry storms, generated auth, docstring bloat.",
      "One-click copy or download. No sign-up, no tracking.",
    ],
    stack: ["Next.js 16", "React 19", "TypeScript", "Tailwind 4"],
    image: "/projects/claude-md-tool.jpg",
    imageAlt: "CLAUDE.md Generator UI — form + live markdown preview",
    links: [
      { label: "Open the tool →", href: "/tools/claude-md" },
      { label: "Read case study →", href: "/projects/claude-md-generator" },
      { label: "Playbook repo →", href: "https://github.com/Regat1ve/claude-code-playbook" },
    ],
    caseStudy: {
      tagline: "Free tool that generates an opinionated CLAUDE.md for your stack and stage. Runs in the browser, no signup.",
      problem: "Most repos I look at either skip CLAUDE.md entirely or paste a stale template from someone else's project. Both cases produce the same failure — Claude Code writes code that fights your stack, and you spend review time cutting it. The fix is a real CLAUDE.md written from experience, not generic best practices.",
      approach: [
        "One page, one form, one output. No sign-up, no server storage, no tracking beyond Vercel's built-in.",
        "Modular by stack: Next.js, React+Vite, Prisma, Auth.js, MapLibre, Express, TanStack Table, Python ETL, PostgreSQL, i18next.",
        "Rules parameterized by project stage — pre-launch bias toward simplicity, growth adds observability, mature adds zero-downtime migration rules.",
        "Each rule written from an actual Claude Code failure I lived through on MedKompas or newforms.",
        "Copy or download. Client-side generation, no round trip to a server.",
      ],
      aiSplit: {
        claude: [
          "The form scaffold (checkboxes, radios, layout).",
          "First draft of the copy/download logic.",
        ],
        me: [
          "Every single rule string. These have to come from real experience or the tool is worthless.",
          "The decision to keep it a static client component instead of a Next.js API route.",
          "The visual design — Claude wanted more color, I cut most of it.",
        ],
      },
      outcome: "Live at /tools/claude-md on this site. Open source under MIT. Rule set will grow as I ship more projects.",
      lessons: [
        "The best CLAUDE.md rule is one that names a specific past failure. Vague best-practice bullets do nothing.",
        "For a tool this focused, no backend beats a backend. Zero cost to run, zero privacy story to write.",
        "Ship the smallest thing that solves the problem for one person (me). If it survives that, expand.",
      ],
    },
  },
];
